### ISSUE TITLE
[Odoo 16.5] ValueError: Module report_csv: invalid manifest

### ISSUE THREAD

**Issue by fractalf** [OCA/reporting-engine#786] opened 2023-08-24 08:31 UTC
This is the core error: 

```
ValueError: Invalid version '16.0.1.0.1'. Modules should have a version in format `x.y`, `x.y.z`, `16.5.x.y` or `16.5.x.y.z`.
```

Setting the version to `16.0.1` fixes the problem. Why the funny version format anyway? :)

Full error
```
2023-08-24 08:29:23,250 51 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 343, in load_manifest
    manifest['version'] = adapt_version(manifest['version'])
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 446, in adapt_version
    raise ValueError(f"Invalid version {base_version!r}. Modules should have a version in format `x.y`, `x.y.z`,"
ValueError: Invalid version '16.0.1.0.1'. Modules should have a version in format `x.y`, `x.y.z`, `16.5.x.y` or `16.5.x.y.z`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2145, in __call__
    if self.get_static_file(httprequest.path):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2041, in get_static_file
    if (module not in self.statics or static != 'static' or not resource):
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 28, in __get__
    value = self.fget(obj)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2011, in statics
    manifest = get_manifest(module)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 363, in get_manifest
    return load_manifest(module, mod_path)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 345, in load_manifest
    raise ValueError(f"Module {module}: invalid manifest") from e
ValueError: Module report_csv: invalid manifest
```

**Comment by legalsylvain** [comment] 2023-08-24 09:20
Hi. Afaik, you try to install an OCA module for version 16.0 on an 16.5 instance. 
That's not possible. The oca version are working only on major odoo release. 

You can indeed patch manually the manifest. 

Closing as not a bug.

**Closed as completed by legalsylvain** 2023-08-24 09:20 UTC
Labels: bug

**Comment by fractalf** [comment] 2023-08-24 09:23
@legalsylvain Hi, ok thanks fair enough.

Any reason why you use this weird format system? 
It would be nice to prepare for the next version anyway

**Comment by legalsylvain** [comment] 2023-08-24 09:42
> Any reason why you use this weird format system?

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#version-numbers

**Comment by fractalf** [comment] 2023-08-24 10:07
Ok. Well, now you at least know this will break in Odoo 17

**Comment by legalsylvain** [comment] 2023-08-24 15:24
> Ok. Well, now you at least know this will break in Odoo 17

No. The OCA format is allowed : 

 or `16.5.x.y.z`.

**Comment by fractalf** [comment] 2023-08-25 08:11
Ah ok, thanks.
Changing it to `16.5.1.0.1` indeed works.
