### ISSUE TITLE
py3o report: No module named py3o.template

### ISSUE THREAD

**Issue by diezcode** [OCA/reporting-engine#340] opened 2019-10-30 09:07 UTC
I have followed the installation documentary from report py3o on my Ubuntu 18.04 Server:

> Install the required python libs:
pip install py3o.template
pip install py3o.formats
To allow the conversion of ODT or ODS reports to other formats (PDF, DOC, DOCX, etc.), install libreoffice:
apt-get --no-install-recommends install libreoffice

I installed this with pip3 too, so I have both, pip and pip3.
I uploaded the report py3o module on my odoo instance. Now when I click "install" I get this error:

> Unable to install module "report_py3o" because an external dependency is not met: No module named py3o.template

Why? I need help on this.

Thank you so much!

**Comment by diezcode** [comment] 2019-10-31 13:00
it seems that with an requirements.txt file:
py3o.template
py3o.formats

it works?! strange

**Comment by lmignon** [comment] 2019-11-19 13:08
@diezcode I close this issue since it seems related to your env (tested locally and I 'm not able to reproduce it).

**Closed as completed by lmignon** 2019-11-19 13:08 UTC

**Comment by OmniaGit** [comment] 2025-12-03 13:31
I have the some problem installing it on odoo **v18** using virtualenv on **Python 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0] on linux**


**pip install**

```
Requirement already satisfied: py3o.template in ./python_odoo_test/lib/python3.11/site-packages (from -r /tmp/requireme.txt (line 1)) (0.10.0)
Requirement already satisfied: py3o.formats in ./python_odoo_test/lib/python3.11/site-packages (from -r /tmp/requireme.txt (line 2)) (0.3)
Requirement already satisfied: Pillow in ./python_odoo_test/lib/python3.11/site-packages (from py3o.template->-r /tmp/requireme.txt (line 1)) (9.4.0)
Requirement already satisfied: babel in ./python_odoo_test/lib/python3.11/site-packages (from py3o.template->-r /tmp/requireme.txt (line 1)) (2.10.3)
Requirement already satisfied: genshi>=0.7 in ./python_odoo_test/lib/python3.11/site-packages (from py3o.template->-r /tmp/requireme.txt (line 1)) (0.7.10)
Requirement already satisfied: lxml in ./python_odoo_test/lib/python3.11/site-packages (from py3o.template->-r /tmp/requireme.txt (line 1)) (4.9.3)
Requirement already satisfied: pyjon.utils>0.6 in ./python_odoo_test/lib/python3.11/site-packages (from py3o.template->-r /tmp/requireme.txt (line 1)) (0.7)
Requirement already satisfied: setuptools in ./python_odoo_test/lib/python3.11/site-packages (from py3o.template->-r /tmp/requireme.txt (line 1)) (66.1.1)
Requirement already satisfied: six>=1.9 in ./python_odoo_test/lib/python3.11/site-packages (from py3o.template->-r /tmp/requireme.txt (line 1)) (1.17.0)
Requirement already satisfied: pytz>=2015.7 in ./python_odoo_test/lib/python3.11/site-packages (from babel->py3o.template->-r /tmp/requireme.txt (line 1)) (2025.1)
```

**odoo log**
```
INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.button_install on ['Py3o Report Engine'] to user admin #2 via 77.244.103.103 
2025-12-03 13:26:58,498 1409571 WARNING odoo odoo.http: Unable to install module "report_py3o" because an external dependency is not met: Package `packaging` is required to parse `py3o.template` external dependency and is not installed 
```

**python venv**
```
Python 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from py3o.formats import Formats
>>> 
```
