### ISSUE TITLE
[16.0]sql_request_abstract widget ACE causing Web issues

### ISSUE THREAD

**Issue by flotho** [OCA/reporting-engine#803] opened 2023-10-20 05:51 UTC
## Module
sql_export but more specifically the view and widget is placed in sql_request_abstract

## Describe the bug
When the query field is empty clicking in this field is causing the issue
![image](https://github.com/OCA/reporting-engine/assets/1043935/a37f746e-9533-448d-8ec9-404f1a72631d)

impossible to type in a query

## To Reproduce
**Affected versions**: 16.0.2 with the ace library

1. intsall the 16.0.2 version
2. create a new query
3. try to input in the query field

**Expected behavior**
no issue

**Additional context**
We tested with older release 16.0.1.0.1 and it worked
we tested with the 16.0.2 and disablbing the ace widget and it worked.
We re add the widget ace on the view and it failed even with a query already present in the field

We're also using the web_responvive module but didn't dig further to find out if this could be a conflict

**Comment by legalsylvain** [comment] 2023-10-20 07:19
Hi @flotho.Thanks for reporting !
I tried to reproduce your problem on runboat without success. Could you investigate ?

Thanks !

**Comment by gabriel-grinspan** [comment] 2023-12-27 19:13
@legalsylvain @flotho 
I experienced the same issue running the latest build of enterprise 16.0 with the following modules installed:
- bi_sql_editor
- bi_view_editor
- bi_view_editor_spreadsheet_dashboard
- sql_export
- sql_request_abstract

I seems that there is something wrong with the custom syntax formatter for SQL. I found that removing `{'mode': 'pgsql'}` from sql_request_abstract/views/view_sql_request_mixin.xml:71 temporarily fixes it.

It also looks like this is somehow not an issue in runboat. Perhaps there is some kind of missing import that wasn't set up properly for some of the modules.

**Comment by legalsylvain** [comment] 2023-12-27 20:40
hi @gabriel-grinspan. Same answer. Please reproduce the error on runboat, as I can investigate.

Note : @flotho : i don't understand the version you mention. We have an active instance of 16.0 version with the module installed and working correctly.
- sql_request_abstract : 16.0.1.0.0 (This is the latest version)
- bi_sql_editor : 16.0.1.0.3 (latest is 16.0.1.1.0)

There is no 16.0.2 version. or did I missed something ?

**Comment by gabriel-grinspan** [comment] 2023-12-27 21:35
@legalsylvain 
I tried to reproduce this in runboat and in my local environment running enterprise and it is working. However, when I test it in one of my other environments, even after upgrading a bunch of apps (including base), I'm still getting the above error. It seems like the Javascript is not properly being loaded or that a hook has changed between builds versions of Odoo. Can you explain how Odoo is supposed to load the JS without an import in the manifest file?

**Comment by legalsylvain** [comment] 2023-12-27 22:46
> I tried to reproduce this in runboat and in my local environment running enterprise and it is working

Thanks ! So closing.

> Can you explain how Odoo is supposed to load the JS without an import in the manifest file?

What do you mean ?

**Closed as completed by legalsylvain** 2023-12-27 22:46 UTC
Labels: bug

**Comment by gabriel-grinspan** [comment] 2023-12-27 22:52
I'm not seeing the Javascript file that is failing to import for @flotho and me being imported in the manifest https://github.com/OCA/reporting-engine/blob/16.0/sql_request_abstract/__manifest__.py
How does this work?

Also I tested in my browser dev tools, and the error is the same when you change `'mode': 'pgsql'` to something else. This indicates that the file is not loading properly.

**Comment by legalsylvain** [comment] 2023-12-27 23:49
> I'm not seeing the Javascript file that is failing to import for @flotho 

I guess you talk about the ``mode-pgsql.js`` ? it is done and explained in the controller : 

https://github.com/OCA/reporting-engine/blob/16.0/sql_request_abstract/controllers/main.py#L12

regards.
