### ISSUE TITLE
[14.0] BI SQL Editor - Materialize View Deleted After Odoo.sh Rebuild

### ISSUE THREAD

**Issue by jtempletmg** [OCA/reporting-engine#822] opened 2023-12-04 19:59 UTC
## Module
reporting-engine

## Describe the bug
I created a materialized view via the BI SQL Editor module.  I then pushed some code changes to our odoo.sh environment.  Once the branch rebuilds the materialized view is gone.

## To Reproduce
**Affected versions**: 14.0

1. Create a view and mark as materialized
2. Push a code change to the same odoo.sh branch
3. Try to access the view's data view the "Open View" menu on the sql view form.

**Expected behavior**
The view should not be deleted.

**Additional context**
Is this perhaps related to the fact that my view is materialized and/or I'm running on odoo.sh?

**Comment by legalsylvain** [comment] 2023-12-04 20:07
Hi @jtempletmg. Thanks for reporting. Could you try to reproduce the problem on the OCA runboat, and here the result ? 
thanks !

**Comment by jtempletmg** [comment] 2023-12-04 20:14
@legalsylvain I'm not sure how to push a code change or trigger a rebuild in the OCA runboat.

**Comment by legalsylvain** [comment] 2023-12-04 21:00
I'm not sure what to do with that issue. I don't know how odoo.sh works. In fact, nobody knows, as the code is not opensource.
Changing code should not generate issue in the bi_sql_editor. Without odoo.sh, I change each month the base code of my instance, and i never had such problem since 6 years. 
is it possible to restart totally your instance on odoo.sh ? 

anyway, If this problem is not reproducible, propose to close it. If you find a way to reproduce it on runboat, or on a local instance, please feel free to reopen with the step to reproduce.

Thanks.

**Closed as completed by legalsylvain** 2023-12-04 21:00 UTC
Labels: bug
